version: '3.8'

services:
  # O kali-aula7 não será iniciado por padrão neste lab (aula 7),
  # já que o Wireshark será instalado localmente no host do aluno.
  # Ele permanece aqui para organização e uso em futuras aulas, se necessário.
  kali-aula7:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali-aula7
    # Manter as capabilities para futuras aulas onde o Kali pode ser ativo
    cap_add:
      - NET_ADMIN
    # Não vamos mais forçar DISPLAY aqui, pois Wireshark é local no host
    # environment:
    #   - DISPLAY=${DISPLAY}
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    volumes:
      - ./shared_volume:/mnt/shared # Manter volume compartilhado se for útil futuramente
    networks:
      - kensei_network

  web-server-aula7:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web-server-aula7
    ports:
      - "8080:8080" # Porta da aplicação web no host para fácil acesso
    networks:
      - kensei_network

networks:
  kensei_network:
    driver: bridge