version: '3.8'

services:
  # O kali-aula7 não será iniciado por padrão neste lab (aula 7),
  # Ele permanece aqui para organização e uso em futuras aulas, se necessário.

  web-server-aula7:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web-server-aula7
    ports:
      - "8080:8080" # Porta da aplicação web no host para fácil acesso
    networks:
      - kensei_network

networks:
  kensei_network:
    driver: bridge