services:
  ubuntu_lab:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu_lab
    entrypoint: ["/bin/bash", "-c"]
    command: bash -c "\
      apt update && \
      apt install -y iputils-ping openssl && \
      cp /flag/id_rsa.pem /root/id_rsa.pem && \
      echo 'Xl2SvVlv+e4QkLk5LoG4a2ZiavwJGy43rGDHwnCwZnpYLJ02pZvk+ihTMqFkdD4U9QbwKsqTpesmFxcKUliwWWSYrkLFAgyfMPbiLsstdiwz95O46cw5s8Fl+KNvfxPkwIoSMQJMgZQ5bEh1RIlXys1aGdAOTwy8yECscnjy9Juu21xVcRhUiQH2Gnw2PnCSfJ2S44Zc3Ebj3ZT04durWZ5IdO/nBbFQASHwegzPOnXOkyvOWKjnk6ly0Ef+LfJt60BP2CiJijZoq0S6hzZd957uV2AC5G9FOVwlyXIkMVOchavjpIbJajotVzNnAVUdnGIc2pqqJYvspvXp97zHrg==' | base64 -d > /root/FLAG.txt && \
      bash"
    volumes:
      - .:/flag:ro
    tty: true
    networks:
      cyberlab:
        ipv4_address: 172.28.1.10

  kali_lab:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali_lab
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp:unconfined
    networks:
      cyberlab:
        ipv4_address: 172.28.1.20

  dvwa_lab:
    build:
      context: .
      dockerfile: Dockerfile.dvwa
    container_name: dvwa_lab
    ports:
      - "8080:80"
    environment:
      - MYSQL_PASS=p@ssw0rd
    networks:
      cyberlab:
        ipv4_address: 172.28.1.30

networks:
  cyberlab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16